services:
  - type: web
    name: social-network
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
