services:
  - type: web
    name: social-network
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
